load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "common",
    srcs = [
        "env.go",
    ],
    importpath = "github.com/IRIO-ORG/Trading-System/common",
    visibility = ["//visibility:public"],
    deps = [
    ],
)
